services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=whatsappclone
      - CASSANDRA_NUM_TOKENS=1

  redis:
    image: redis:latest
    container_name: redis
    command: [
      "redis-server",
      "--maxmemory","250mb",
      "--maxmemory-policy","allkeys-lfu"
    ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  cassandra_data:

