services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=LocalCluster
      - CASSANDRA_NUM_TOKENS=1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q 'UN'"]
      interval: 30s
      timeout: 10s
      retries: 10

  redis:
    image: redis:latest
    command: [
      "redis-server",
      "--maxmemory","250mb",
      "--maxmemory-policy","allkeys-lfu"
    ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  cassandra_data:

